<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-04-08">

<title>More on Python</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="lesson11_files/libs/clipboard/clipboard.min.js"></script>
<script src="lesson11_files/libs/quarto-html/quarto.js"></script>
<script src="lesson11_files/libs/quarto-html/popper.min.js"></script>
<script src="lesson11_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lesson11_files/libs/quarto-html/anchor.min.js"></script>
<link href="lesson11_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lesson11_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lesson11_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lesson11_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lesson11_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>

      .quarto-title-block .quarto-title-banner {
        background: #002f8b;
      }
</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">More on Python</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">April 8, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-you-should-already-know" id="toc-what-you-should-already-know" class="nav-link active" data-scroll-target="#what-you-should-already-know"><span class="header-section-number">1</span> What you should already know</a></li>
  <li><a href="#data-types-constants-and-variables" id="toc-data-types-constants-and-variables" class="nav-link" data-scroll-target="#data-types-constants-and-variables"><span class="header-section-number">2</span> Data types, constants, and variables</a></li>
  <li><a href="#input-and-output" id="toc-input-and-output" class="nav-link" data-scroll-target="#input-and-output"><span class="header-section-number">3</span> Input and output</a></li>
  <li><a href="#operators" id="toc-operators" class="nav-link" data-scroll-target="#operators"><span class="header-section-number">4</span> Operators</a></li>
  <li><a href="#primary-control-constructs" id="toc-primary-control-constructs" class="nav-link" data-scroll-target="#primary-control-constructs"><span class="header-section-number">5</span> Primary control constructs</a></li>
  <li><a href="#subprograms" id="toc-subprograms" class="nav-link" data-scroll-target="#subprograms"><span class="header-section-number">6</span> Subprograms</a></li>
  <li><a href="#a-review-of-program-flow" id="toc-a-review-of-program-flow" class="nav-link" data-scroll-target="#a-review-of-program-flow"><span class="header-section-number">7</span> A review of program flow</a></li>
  <li><a href="#formal-vs-actual-parameters" id="toc-formal-vs-actual-parameters" class="nav-link" data-scroll-target="#formal-vs-actual-parameters"><span class="header-section-number">8</span> Formal vs actual parameters</a></li>
  <li><a href="#variable-scope" id="toc-variable-scope" class="nav-link" data-scroll-target="#variable-scope"><span class="header-section-number">9</span> Variable scope</a></li>
  <li><a href="#a-review-of-the-python-list" id="toc-a-review-of-the-python-list" class="nav-link" data-scroll-target="#a-review-of-the-python-list"><span class="header-section-number">10</span> A review of the Python list</a></li>
  <li><a href="#revisiting-searching-and-sorting-in-python" id="toc-revisiting-searching-and-sorting-in-python" class="nav-link" data-scroll-target="#revisiting-searching-and-sorting-in-python"><span class="header-section-number">11</span> Revisiting searching and sorting in Python</a></li>
  <li><a href="#other-operators" id="toc-other-operators" class="nav-link" data-scroll-target="#other-operators"><span class="header-section-number">12</span> Other operators</a></li>
  <li><a href="#string-methods" id="toc-string-methods" class="nav-link" data-scroll-target="#string-methods"><span class="header-section-number">13</span> String methods</a></li>
  <li><a href="#importing-extertan-libraries" id="toc-importing-extertan-libraries" class="nav-link" data-scroll-target="#importing-extertan-libraries"><span class="header-section-number">14</span> Importing extertan libraries</a></li>
  <li><a href="#programming-languages" id="toc-programming-languages" class="nav-link" data-scroll-target="#programming-languages"><span class="header-section-number">15</span> Programming Languages</a></li>
  <li><a href="#programming-paradigms" id="toc-programming-paradigms" class="nav-link" data-scroll-target="#programming-paradigms"><span class="header-section-number">16</span> Programming Paradigms</a></li>
  <li><a href="#why-python" id="toc-why-python" class="nav-link" data-scroll-target="#why-python"><span class="header-section-number">17</span> Why Python?</a></li>
  <li><a href="#integrated-development-environments-ides" id="toc-integrated-development-environments-ides" class="nav-link" data-scroll-target="#integrated-development-environments-ides"><span class="header-section-number">18</span> Integrated Development Environments (IDEs)</a></li>
  <li><a href="#scratch-vs.-python" id="toc-scratch-vs.-python" class="nav-link" data-scroll-target="#scratch-vs.-python"><span class="header-section-number">19</span> Scratch vs.&nbsp;Python</a></li>
  <li><a href="#python-primer" id="toc-python-primer" class="nav-link" data-scroll-target="#python-primer"><span class="header-section-number">20</span> Python Primer</a>
  <ul class="collapse">
  <li><a href="#creating-programs-and-saving-files" id="toc-creating-programs-and-saving-files" class="nav-link" data-scroll-target="#creating-programs-and-saving-files"><span class="header-section-number">20.1</span> Creating Programs and Saving Files</a></li>
  <li><a href="#reloading-a-saved-file" id="toc-reloading-a-saved-file" class="nav-link" data-scroll-target="#reloading-a-saved-file"><span class="header-section-number">20.2</span> Reloading a saved file</a></li>
  <li><a href="#data-types-constants-and-variables-1" id="toc-data-types-constants-and-variables-1" class="nav-link" data-scroll-target="#data-types-constants-and-variables-1"><span class="header-section-number">20.3</span> Data types, constants, and variables</a></li>
  <li><a href="#input-and-output-1" id="toc-input-and-output-1" class="nav-link" data-scroll-target="#input-and-output-1"><span class="header-section-number">20.4</span> Input and Output</a></li>
  <li><a href="#expressions-and-assignment" id="toc-expressions-and-assignment" class="nav-link" data-scroll-target="#expressions-and-assignment"><span class="header-section-number">20.5</span> Expressions and assignment</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">





<section id="what-you-should-already-know" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="what-you-should-already-know"><span class="header-section-number">1</span> What you should already know</h2>
<p>In this lesson, we will build on what you have already learned about the Python programming language. To be sure that we are all on the same page, let’s briefly review the things about Python that you should already be familiar with. For more detail, review the lesson on <em>Introduction to Computer Programming</em>.</p>
</section>
<section id="data-types-constants-and-variables" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="data-types-constants-and-variables"><span class="header-section-number">2</span> Data types, constants, and variables</h2>
<p>You should know that the kinds of calues that cen be expressed in a programming language are known as its <strong>data types</strong>. The <strong>primitive types</strong> of a programming language are those data types that are built-in (or standard) to the language and typically considered as basic building blocks (i.e., more complex types can be created from these primitive types). Python’s standard types can be grouped into several classes: numeric types, sequences, sets, and mappings. You should be familiar with numeric types and sequences (e.g., lists)</p>
<p>You should know that a <strong>constant</strong> is defined as a value of a particular type that does not change over time. In Python both numbers and text may be expressed as constants. <strong>Numeric constants</strong> are composed of the digits 0 through 9 and, optionally, a negative sign (for negative numbers), and a decimal point (for floating point numbers). <strong>Text constants</strong> consists of a sequence of characters (also known as a string of characters – or just a <strong>string</strong>).</p>
<p>You should know that a <strong>variable</strong> is defined to be a named object that can store a value of a particular type. Before a variable can be used, its name must be declared.</p>
</section>
<section id="input-and-output" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="input-and-output"><span class="header-section-number">3</span> Input and output</h2>
<p>You should be familiar with obtaining input (via the input function) and generating output (via the <code>print</code> statement) in Python. Here’s a simple example:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>name <span class="op">=</span> <span class="bu">input</span>(<span class="st">"What is your name? "</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Hello, </span><span class="sc">{}</span><span class="st">!"</span>.<span class="bu">format</span>(name))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="operators" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="operators"><span class="header-section-number">4</span> Operators</h2>
<p>You should be familiar with a variety of operators in Python. Specifically, arithmetic operators, relational (comparison) operators, and assignment operators. Arithmetic operators include addition, subtraction, etc, and perform arithmetic operations on operands. Relational operators include comparison of equality, inequality, less-than, and so on, and perform comparisons on operands and return true or false. Assignment operators include operators such as +=, -=, and so on, and combine assignment with arithmetic.</p>
</section>
<section id="primary-control-constructs" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="primary-control-constructs"><span class="header-section-number">5</span> Primary control constructs</h2>
<p>You should be very familiar with the three primary control constructs: sequence, selection, and repetition. Sequence implies one statement after another. Selection allows blocks of optional statements to be executed. Repetition provides a mechanism for repeating blocks of statements. There are two main forms of repetition that we have covered: iteration and recursion. Iteration involves repeating a task some fixed number of times, until a condition is reached, or over some structure (such as the items in a list). Although recursion was only briefly covered, you should know that it involves breaking a problem down repeatedly into smaller versions of itself until a base or trivial case is reached. We will cover recursion in much more detail later in the curriculum.</p>
</section>
<section id="subprograms" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="subprograms"><span class="header-section-number">6</span> Subprograms</h2>
<p>You should be quite familiar with subprograms and how they can encapsulate behavior in programs. They are organized, reusable, and related statements that perform some action. Specifically, some subprograms perform tasks and terminate; others return a value. You should understand how control flow is transferred to a subprogram when a subprogram is called, and how it is returned when the subprogram terminates</p>
</section>
<section id="a-review-of-program-flow" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="a-review-of-program-flow"><span class="header-section-number">7</span> A review of program flow</h2>
<p>Although you should be familiar with this already, it is so important that we should probably go over it in detail again. It is very important to be able to identify the flow of control in any program, particularly to understand what is going on. In fact, this significantly helps to debug problems in programs. Recall that, in Python, function definitions aren’t executed in the order that they are written in the source code. Functions are only executed when they are called. This is perhaps best illustrated with an example that you have seen before:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a> <span class="dv">1</span>: <span class="kw">def</span> <span class="bu">min</span>(a, b):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a> <span class="dv">2</span>: <span class="cf">if</span> (a <span class="op">&lt;</span> b):</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a> <span class="dv">3</span>: <span class="cf">return</span> a</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a> <span class="dv">4</span>: <span class="cf">else</span>:</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a> <span class="dv">5</span>: <span class="cf">return</span> b</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a> <span class="dv">6</span>: <span class="kw">def</span> <span class="bu">max</span>(a, b):</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a> <span class="dv">7</span>: <span class="cf">if</span> (a <span class="op">&gt;</span> b):</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a> <span class="dv">8</span>: <span class="cf">return</span> a</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a> <span class="dv">9</span>: <span class="cf">else</span>:</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span>: <span class="cf">return</span> b</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="dv">11</span>: num1 <span class="op">=</span> <span class="bu">int</span>(<span class="bu">input</span>(<span class="st">"Enter a number: "</span>))</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="dv">12</span>: num2 <span class="op">=</span> <span class="bu">int</span>(<span class="bu">input</span>(<span class="st">"Enter another number: "</span>))</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="dv">13</span>: <span class="bu">print</span>(<span class="st">"The smaller is </span><span class="sc">{}</span><span class="st">."</span>.<span class="bu">format</span>(<span class="bu">min</span>(num1, num2)))</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="dv">14</span>: <span class="bu">print</span>(<span class="st">"The larger is </span><span class="sc">{}</span><span class="st">."</span>.<span class="bu">format</span>(<span class="bu">max</span>(num1, num2)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Each Python statement is numbered for reference. Lines 1 through 5 represent the definition of the function <code>min</code>. This function returns the <em>minimum</em> of two values provided as parameters. Lines 6 through 10 represent the definition of the function <code>max</code>. This function returns the <em>maximum</em> of two values provided as parameters. Lines 11 through 14 represent the main part of the program. Although the Python interpreter does <em>see</em> lines 1 through 10, those lines are not actually <em>executed</em> until the functions <code>min</code> and <code>max</code> are actually called. The first line of the program to actually be executed is line 11. In fact, here is the order of the statements executed in this program if <em>num1</em> = 34 and <em>num2</em> = 55:</p>
<p><span class="math display">\[ 11,12,13,1,2,3,14,6,7,9,10 \]</span></p>
<p>Let’s explain. Line 11 asks the user to provide some value for the first number (which is stored in the variable <em>num1</em>). Line 12 asks the user to provide some value for the second number (which is stored in the variable <em>num2</em>). Line 13 displays some text; however, part of the text must be obtained by first calling the function <code>min</code>. This transfers control to line 1 (where <code>min</code> is defined). The two actual parameters, <em>num1</em> and <em>num2</em>, are then passed in and mapped to the formal parameters defined in <code>min</code>, <em>a</em> and <em>b</em>. Then, line 2 is executed and performs a comparison of the two numbers. Since <em>a</em> = 34 and <em>b</em> = 55, then the condition in the if-statement is true. Therefore, line 3 is executed before control is transferred back to the main program with the value of the smaller number returned (and then control continues on to line 14). Note that lines 4 and 5 are never executed in this case!</p>
<p>Line 14 is then executed and displays some text. Again, part of the text must be obtained by first calling the function <code>max</code>. This transfers control to line 6 (where <code>max</code> is defined). The variables <em>a</em> and <em>b</em> take on the values 34 and 55 respectively. Line 7 is then executed, and the result of the comparison is false. Therefore, line 8 is not executed. Control then goes to line 9, and then to line 10 which returns the larger value. The program then ends.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Activity">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Activity
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>What is the order of execution if <em>num1</em> = 55 and <em>num2</em> = 34?</p>
<p>What if <em>num1</em> = 100 and <em>num2</em> = 100?</p>
</div>
</div>
</div>
<p>Here’s another example with a simple for loop:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span>:  <span class="cf">for</span> a <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">4</span>):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span>:    <span class="cf">for</span> b <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">5</span>):</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="dv">3</span>:      <span class="bu">print</span>(<span class="st">"</span><span class="sc">{}</span><span class="st"> * </span><span class="sc">{}</span><span class="st"> = </span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(a, b, a <span class="op">*</span> b))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This snippet of code displays a portion of a multiplication table. In fact, run this to see the output:</p>
<div id="12889af3" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> a <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">4</span>):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> b <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">5</span>):</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"</span><span class="sc">{}</span><span class="st"> * </span><span class="sc">{}</span><span class="st"> = </span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(a, b, a <span class="op">*</span> b))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12</code></pre>
</div>
</div>
<p>Here’s the order of the statements executed. To make things a bit more clear, it is grouped and highlighted:</p>
<p><img src="images/Lesson11-01.png" class="img-fluid"></p>
<p>The first portion (highlighted in red and labeled 1 * n) represents a single iteration of the <strong>outer</strong> for loop and a <em>full</em> iteration of the <strong>inner</strong> for loop. It generates the following output:</p>
<pre><code>  1 * 1 = 1
  1 * 2 = 2
  1 * 3 = 3
  1 * 4 = 4</code></pre>
<p>Let’s explain. Line 1 of the outer for loop generates the list [ 1, 2, 3 ]. It then iterates over the values in the list with the variable <em>a</em> taking on each value, one at a time. Initially, <em>a</em> = 1. Line 2 represents the inner for loop and generates the list [ 1, 2, 3, 4 ], and iterates over its values with the variable <em>b</em> taking on each value, one at a time. Initially, <em>b</em> = 1. Line 3 then displays the first line of output: <span class="math inline">\(1 * 1 = 1\)</span>. This makes sense because <em>a</em> and <em>b</em> are both 1.</p>
<p>So far, the order of statements executed is 1, 2, 3. Note that the inner for loop iterates its complete cycle (i.e., through the entire generated list) for each iteration of the outer for loop. Therefore, the inner for loop iterates through the list [ 1, 2, 3, 4 ] for each value in the outer for loop’s list [ 1, 2, 3 ]. After line 3 (when <em>a</em> and <em>b</em> are both 1), the inner for loop then iterates to the next value in the list. Therefore, line 2 is executed again so that <em>b</em> = 2. Similarly, line 3 executes again, generating the output: <span class="math inline">\(1 * 2 = 2\)</span>. At this point, the order of statements executed is 1, 2, 3, 2, 3.</p>
<p>The inner for loop continues iterating two more times (lines 2 and 3), setting <em>b</em> to 3 and then to 4. After the first full iteration of the outer for loop, the order of statements executed is 1, 2, 3, 2, 3, 2, 3, 2, 3. So when <em>a</em> = 1, <em>b</em> goes through the values 1, 2, 3, and 4. The output generated at this point is then:</p>
<pre><code>  1 * 1 = 1
  1 * 2 = 2
  1 * 3 = 3
  1 * 4 = 4</code></pre>
<p>Since the inner for loop has finished a full iteration, control goes back to line 1, thereby allowing the outer for loop to iterate to the next value in the list so that <em>a</em> = 2. Line 2 is executed again, generating a new list [ 1, 2, 3, 4 ] and setting <em>b</em> to 1. Similarly, line 3 is executed again, generating the output: <span class="math inline">\(2 * 1 = 2\)</span>. Lines 2 and 3 are executed as before, for each value in the inner loop’s list [ 1, 2, 3, 4 ]. Of course, this generates exactly the same order of statements as before: 1, 2, 3, 2, 3, 2, 3, 2, 3. However, this represents the second iteration of the outer loop.</p>
<p>Since the inner for loop has finished another full iteration, control goes back to line 1, thereby allowing the outer for loop to iterate to the next value in the list so that <em>a</em> = 3. Again, lines 2 and 3 are executed as before, for each value in the inner loop’s list [ 1, 2, 3, 4 ]. Clearly, this generates exactly the same order of statements as before: 1, 2, 3, 2, 3, 2, 3, 2, 3. This time, it represents the third (and final) iteration of the outer loop. Why? Because the outer for loop has iterated through the entire list [ 1, 2, 3 ]. After this final iteration, the variable <em>a</em> has taken on all of these values. Therefore, the outer for loop is exited, and the program terminates.</p>
<p>Again, knowing the order in which statements are executed is crucial to debugging programs and ultimately to creating programs that work.</p>
<p>This concludes a review of what you should already know in Python. From here, we’ll introduce new content.</p>
</section>
<section id="formal-vs-actual-parameters" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="formal-vs-actual-parameters"><span class="header-section-number">8</span> Formal vs actual parameters</h2>
<p>You have seen that a function can have parameters. These parameters are formally stated when the function is defined; for example:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> average(a, b):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> (a <span class="op">+</span> b) <span class="op">/</span> <span class="fl">2.0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Here, the variables <em>a</em> and <em>b</em> are formally defined as parameters that must be passed in to the function <code>average</code> when it is called. In this context, the variables a and b are called formal <strong>parameters</strong>. It is where they are defined (in a formal manner).</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Formal parameters</strong> are formally defined as part of the function header</p>
</div>
</div>
<p>Now consider a point in the source code where this function is called; for example:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>avg <span class="op">=</span> average(<span class="dv">11</span>, <span class="dv">67</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Here, the result of a call to the function <code>average</code> with the supplied values (or parameters) 11 and 67 is stored in the variable <em>avg</em>. These values, 11 and 67, are considered <strong>actual parameters</strong> in this context. That is, they are the <em>actual</em> values that will be passed in as parameters to the function <code>average</code>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Actual parameters</strong> (or <strong>arguments</strong>) are the actual values that are passed into a function.</p>
</div>
</div>
<p>In fact, they are mapped to the formally defined parameters (i.e., formal parameters) <em>a</em> and <em>b</em> in the function <code>average</code>. That function will use these values to make calculations and return the average of the two. The value returned replaces the function call. Think of this replacement as follows:</p>
<p><code>avg</code> = <del><code>average(11, 67)</code></del> 39.0</p>
<p>Therefore, the variable <em>avg</em> is assigned the value 39.0 after the call to the function <code>average</code> is complete. Consider this call to the same function:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> <span class="dv">11</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> <span class="dv">67</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>avg <span class="op">=</span> average(x, y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Here, the result is still the same. The average of the two variables, <em>x</em> and <em>y</em> (with the values 11 and 67 respectively), is stored in the variable <em>avg</em>. Here, <em>x</em> and <em>y</em> are also actual parameters (even if they are variables themselves) because they represent the actual values supplied to the function <code>average</code>.</p>
</section>
<section id="variable-scope" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="variable-scope"><span class="header-section-number">9</span> Variable scope</h2>
<p>Consider the following Python program snippet and its output:</p>
<div id="54006c11" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>a <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> f(x):</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  a <span class="op">=</span> <span class="dv">11</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  b <span class="op">=</span> <span class="dv">21</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  x <span class="op">*=</span> <span class="dv">2</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="st">"in f(): a=</span><span class="sc">{}</span><span class="st">, b=</span><span class="sc">{}</span><span class="st">, x=</span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(a, b, x))</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> <span class="dv">20</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>f(b)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"in main: a=</span><span class="sc">{}</span><span class="st">, b=</span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(a, b))</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> g():</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="kw">global</span> a</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  a <span class="op">*=</span> <span class="fl">1.5</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="st">"in g(): a=</span><span class="sc">{}</span><span class="st">, b=</span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(a, b))</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>g()</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"in main: a=</span><span class="sc">{}</span><span class="st">, b=</span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(a, b))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>in f(): a=11, b=21, x=40
in main: a=10, b=20
in g(): a=15.0, b=20
in main: a=15.0, b=20</code></pre>
</div>
</div>
<p>The variables <em>a</em> and <em>b</em> are considered global variables</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Global variables</strong> are accessible throughout the entire program because they are defined outside of any block context (e.g., a loop construct, a function, etc). Global variables can be accessed anywhere. Their <strong>scope</strong> is global (i.e., throughout the entire program).</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>A variable’s <strong>scope</strong> is the region of code that variable is accessible in.</p>
</div>
</div>
<p>Take a look at the output of the program above:</p>
<pre><code>  in f(): a=11, b=21, x=40
  in main: a=10, b=20
  in g(): a=15.0, b=20
  in main: a=15.0, b=20</code></pre>
<p>Let’s explain the output. Initially, the variable <em>a</em> is assigned the value 10. The next segment of code defines the function <code>f</code>. This is only a definition (i.e., the statements are not actually interpreted or executed at this point). Then, the variable <em>b</em> is assigned the value 20. What follows is a call to the function <code>f</code>, passing the variable <em>b</em> as an actual parameter. Control is then transferred to the function <code>f</code>, whose statements are now executed. Note that, to the function <code>f</code>, the variable <em>x</em> is the formal parameter that takes on the value passed in (from the variable b). So the variable <em>x</em> is now equal to the value of the variable <em>b</em> (i.e., 20) that was passed in at the point of the call to <code>f</code>. Note that the variable <em>x</em> is local to the function <code>f</code>; therefore, it is considered a local variable. That is, it is defined in <code>f</code> and only accessible in <code>f</code> – its scope is valid only in the function <code>f</code>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>local variable</strong> is a variable defined in (and therefore only accessible in) a local region/context. For example, a variable defined inside a function is <strong>local</strong> to that function and therefore only accessible within that function.</p>
</div>
</div>
<p>Also note that, although <em>a</em> and <em>b</em> are global, there are local versions declared in <code>f</code>. It is important to note that these are different variables than the global versions – even if they have the same name!</p>
<p>A computer can only understand machine language. Machine language instructions are entirely made up of binary digits and can be directly executed by the CPU. Since we have a particularly hard time understanding 1s and 0s, early programmers assigned a set of mnemonics to represent machine code instructions so that they would be a bit more readable. This mapping became known as <strong>assembly language</strong>. People still write code in assembly language, but it is not typically used to create large scale applications.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Shadowing</strong> is the process of introducing a local variable that shares the same name as a global variable. This local variable “shadows” (or hides) access to the global variable of the same name. We will see this concept appear again later in the course, but with a different context</p>
</div>
</div>
<p>So what happens in <code>f</code>? The local variable <em>a</em> is initialized with the value 11, the local variable <em>b</em> is initialized with the value 21, and the local variable <em>x</em> (which is passed in as an argument with the value 20) is doubled to 40. The output of the function <code>f</code> is then clear:</p>
<pre><code>  in f(): a=11, b=21, x=40</code></pre>
<p>Once <code>f</code> completes and control is transferred back to the point at which function <code>f</code> was called, the variable <em>x</em> is no longer accessible! In fact, let’s alter the print statement immediately after the call to <code>f</code> from:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"in main: a=</span><span class="sc">{}</span><span class="st">, b=</span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(a, b))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>And change it to:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"in main: a=</span><span class="sc">{}</span><span class="st">, b=</span><span class="sc">{}</span><span class="st">, x=</span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(a, b, x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Here’s the output of the program now:</p>
<pre><code>in f(): a=11, b=21, x=40
Traceback (most recent call last):
  File "scope.py", line 11, in &lt;module&gt;
    print("in main: a={}, b={}, x={}".format(a, b, x))
NameError: name 'x' is not defined</code></pre>
<p>Notice the error indicating that the variable <em>x</em> is not defined. That’s because it was defined in <code>f</code>; however, the current context is outside of <code>f</code>. The variable <em>x</em> is no longer available once <code>f</code> finishes and control is transferred back to the main part of the program.</p>
<p>Let’s replace the print statement to remove the error and explain the rest of the output from the original execution of the program:</p>
<pre><code>in main: a=10, b=20
in g(): a=15.0, b=20
in main: a=15.0, b=20</code></pre>
<p>Once control is transferred back to the main part of the program, the local variables <em>a</em> and <em>b</em> (in <code>f</code>) no longer exist. However, the global variables <em>a</em> and <em>b</em> do! They were initialized to 10 and 20 respectively. Therefore, the next line of output makes sense:</p>
<pre><code>in main: a=10, b=20</code></pre>
<p>The next part of the program defines another function, <code>g</code>, that is then called. Note the <strong>global</strong> keyword in the function <code>g</code>. This instructs Python to reference a globally defined version of the variable that follows the global keyword. That is, a local version is not defined and/or initialized. Instead, the global version is directly referenced. Moreover (and quite importantly), it permits the global version to be <strong>changed</strong>. Although there are no arguments to the function <code>g</code>, the global variable a is directly <strong>modifiable</strong> through the global keyword. When the statement <code>a *= 1.5</code> is executed, the value of the global variable <em>a</em> is 10. This statement changes its value to 15.0, directly updating the variable’s value – globally!</p>
<p>Note the print statement in <code>g</code>. It refers both to the variables <em>a</em> and <em>b</em>. A reference to the variable <em>a</em> makes sense; however, the variable <em>b</em> is also accessible. In fact, the variable <em>b</em> is referencing the global version of <em>b</em>, similar to the variable <em>a</em> (i.e., it is directly <strong>readable</strong>). The difference in using the global keyword is that it permits a change to the variable; without it, it can only be utilized in a read-only manner. Since the global variable <em>b</em> is initialized with the value 20, the output in <code>g</code> is clear:</p>
<pre><code>in g(): a=15.0, b=20</code></pre>
<p>When control is transferred back to the main part of the program, changes to global variable a persist (even if they were changed in a function!):</p>
<pre><code>in main: a=15.0, b=20</code></pre>
<p>To illustrate this even more, let’s slightly change the function <code>g</code> as follows:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> g():</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="kw">global</span> a</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  a <span class="op">*=</span> <span class="fl">1.5</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  b <span class="op">=</span> <span class="dv">40</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="st">"in g(): a=</span><span class="sc">{}</span><span class="st">, b=</span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(a, b))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Note the slight difference: <em>b</em> is declared and initialized with the value 40. Which <em>b</em> is this? Is it a local version (i.e., local to <code>g</code>)? Or is it referring to the global version declared in the main part of the program? Recall that, without the global keyword, a global variable can not be modified. Therefore, an assignment statement in a function to a variable that has the same name as a global variable indicates that the variable is a new instance, defined <strong>locally</strong> in the function. This is a different variable <em>b</em>! The output in <code>g</code> is clear:</p>
<pre><code>in g(): a=15.0, b=40</code></pre>
<p>When control is transferred back to the main part of the program, the local version of <em>b</em> disappears. All that’s left is the global version (that remains unchanged at 20). Therefore, the output in the main part of the program is also clear:</p>
<pre><code>in main: a=15.0, b=20</code></pre>
</section>
<section id="a-review-of-the-python-list" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="a-review-of-the-python-list"><span class="header-section-number">10</span> A review of the Python list</h2>
<p>Although you should be familiar with Python lists, they are quite important and used often; therefore, we will go over it again. Generally, a Python sequence is composed of (typically related) elements. Each element in a sequence is assigned an index (or position). A sequence with n elements has indexes 0 to n–1. Python has many built-in types of sequences; however, the most popular is called the list. The list in Python is quite versatile. Recall that a list is declared using square brackets; for example:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>grades <span class="op">=</span> [ <span class="dv">94</span>, <span class="dv">78</span>, <span class="dv">100</span>, <span class="dv">86</span> ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The statement above declares the list <code>grades</code> with four integers: 94, 78, 100, and 86. The list can be displayed in its entirety (e.g., with the statement <code>print(grades)</code>); however, we can access each element individually by its index (specified within brackets). Accessing can mean to read a value in the list, or it can mean to change a value in the list; for example:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grades[<span class="dv">0</span>])</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>grades[<span class="dv">3</span>] <span class="op">=</span> <span class="dv">87</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>grades[<span class="dv">1</span>] <span class="op">+=</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Recall that more than one value in a list can be accessed at a time. We can specify a range (or interval) of indexes in the format <code>[lower:upper+1]</code> which means the interval [lower, upper) (i.e., closed at lower and open at upper). That is, the lower index in the range is inclusive but the upper is not. For example:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>stuff[<span class="dv">3</span>:<span class="dv">4</span>] <span class="co"># accesses index 3 (the same as stuff[3])</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>stuff[<span class="dv">0</span>:<span class="dv">5</span>] <span class="co"># accesses indexes 0 through 4</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>stuff[<span class="op">-</span><span class="dv">3</span>] <span class="co"># accesses the third index from the right</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Also recall that list elements can be deleted with the <strong><code>del</code></strong> keyword as follows:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="kw">del</span> stuff[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Finally, recall that Python provides several built-in operations that can be performed on lists. Here are many of them:</p>
<table class="table">
<caption>List Operators</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 81%">
</colgroup>
<thead>
<tr class="header">
<th>Operation</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>len(list)</code></td>
<td style="text-align: left;">Returns the length of a list</td>
</tr>
<tr class="even">
<td><code>max(list)</code></td>
<td style="text-align: left;">Returns the item in the list with the maximum value</td>
</tr>
<tr class="odd">
<td><code>min(list)</code></td>
<td style="text-align: left;">Returns the item in the list with the minimum value</td>
</tr>
<tr class="even">
<td><code>list.append(item)</code></td>
<td style="text-align: left;">Inserts item at the end of the list</td>
</tr>
<tr class="odd">
<td><code>list.count(item)</code></td>
<td style="text-align: left;">Returns the number of times an item appears in the list</td>
</tr>
<tr class="even">
<td><code>list.index(item)</code></td>
<td style="text-align: left;">Returns the index of the first occurrence of item</td>
</tr>
<tr class="odd">
<td><code>list.insert(index, item)</code></td>
<td style="text-align: left;">Inserts an item at the specified index in the list</td>
</tr>
<tr class="even">
<td><code>list.remove(item)</code></td>
<td style="text-align: left;">Removes the first occurrence of item from the list</td>
</tr>
<tr class="odd">
<td><code>list.reverse()</code></td>
<td style="text-align: left;">Reverses the items in the list</td>
</tr>
<tr class="even">
<td><code>list.sort()</code></td>
<td style="text-align: left;">Sorts a list</td>
</tr>
</tbody>
</table>
</section>
<section id="revisiting-searching-and-sorting-in-python" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="revisiting-searching-and-sorting-in-python"><span class="header-section-number">11</span> Revisiting searching and sorting in Python</h2>
<p>In previous lessons, we designed several searching algorithms (sequential/linear search and binary search) and sorting algorithms (bubble sort, selection sort, and insertion sort). We first specified them in pseudocode, and for some we showed how they could be implemented in Python (sequential search, binary search, and selection sort). To help get a better understanding of Python, let’s briefly revisit some of these.</p>
<p>First, here’s the <strong>sequential search</strong> for the smallest value in a list (from an earlier lesson). Note that a Python list is first populated with 20 random integers (from 1 to 99, also from an earlier lesson):</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a> <span class="dv">1</span>: <span class="im">from</span> random <span class="im">import</span> randint</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a> <span class="dv">2</span>: numbers <span class="op">=</span> []</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a> <span class="dv">3</span>: <span class="cf">while</span> (<span class="bu">len</span>(numbers) <span class="op">&lt;</span> <span class="dv">20</span>):</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a> <span class="dv">4</span>:   numbers.append(randint(<span class="dv">1</span>, <span class="dv">99</span>))</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a> <span class="dv">5</span>: <span class="bu">print</span>(numbers)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a> <span class="dv">6</span>: minIndex <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a> <span class="dv">7</span>: <span class="cf">for</span> index <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(numbers)):</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a> <span class="dv">8</span>:   <span class="cf">if</span> (numbers[index] <span class="op">&lt;</span> numbers[minIndex]):</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a> <span class="dv">9</span>:     minIndex <span class="op">=</span> index</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span>: <span class="bu">print</span>(<span class="st">"The smallest value is at index: </span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(minIndex))</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="dv">11</span>: <span class="bu">print</span>(<span class="st">"The smallest value is: </span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(numbers[minIndex]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This version of the sequential search technically returns the <strong>index</strong> of the smallest value (which is typically what programmers are interested in). Since the value can be easily accessed through the index, returning the index is much more meaningful. To generalize the sequential search so that it can return the index of a <em>specified</em> value (as opposed to the smallest value), it can be modified by replacing lines 6 through 11 as follows:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>num <span class="op">=</span> <span class="bu">int</span>(<span class="bu">input</span>(<span class="st">"What integer would you like to search for? "</span>))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(numbers)):</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (numbers[index] <span class="op">==</span> num):</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"The value </span><span class="sc">{}</span><span class="st"> was found at index </span><span class="sc">{}</span><span class="st">!"</span>.<span class="bu">format</span>(num, index))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>What happens if the specified value is duplicated several times in the list? Clearly, each index would be displayed. Here’s example (with user input in bold):</p>
<p><code>[20, 47, 80, 52, 98, 80, 1, 14, 31, 48, 70, 31, 97, 30, 31, 43, 59, 2, 38, 50]</code><br>
<code>What integer would you like to search for?</code> <strong><code>31</code></strong><br>
<code>The value 31 was found at index 8!</code><br>
<code>The value 31 was found at index 11!</code><br>
<code>The value 31 was found at index 14!</code></p>
<p>But what if it’s only necessary to find the <em>first</em> occurrence of a specified value (and then abort)? Python provides a way to <strong>exit a repetition construct early</strong> (a.k.a. an “early exit”) through the <strong><code>break</code></strong> keyword! Formally, the break keyword exits the <em>nearest enclosing</em> repetition construct. More on this in a bit. To illustrate the use of the break keyword, the sequential search code above can be modified to return only the first instance of a specified value:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(numbers)):</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (numbers[index] <span class="op">==</span> num):</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"The value </span><span class="sc">{}</span><span class="st"> was found at index </span><span class="sc">{}</span><span class="st">!"</span>.<span class="bu">format</span>(num, index))</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">break</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Here’s an example:</p>
<p><code>[87, 44, 37, 69, 92, 74, 49, 97, 65, 69, 27, 61, 22, 77, 3, 3, 25, 86, 53, 45]</code><br>
<code>What integer would you like to search for?</code> <strong><code>3</code></strong><br>
<code>The value 3 was found at index 14!</code></p>
<p>Note that the value 3 occurs twice in the list (at index 14 and index 15); however, only the first instance is reported to the user before the search terminates. The break statement exits the enclosing repetition construct: in this case, the for loop.</p>
<p>What if the break keyword is located in a repetition construct that is also located inside of another repetition construct? In this case, it will exit the inner repetition construct only. Here’s an example and output:</p>
<div id="367cbb65" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">2</span>):</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="st">"i=</span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(i)),</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>):</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"j=</span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(j)),</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (j <span class="op">&gt;</span> <span class="dv">1</span>):</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>      <span class="cf">break</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>i=0
j=0
j=1
j=2

i=1
j=0
j=1
j=2
</code></pre>
</div>
</div>
<p>The outer for loops iterates <em>i</em> from 0 through 1. The inner for loop iterates <em>j</em> from 0 through 4. Moreover, the inner for loop exits early if <em>j</em> is greater than 1. Technically, the print statement in the inner for loop will display values of <em>j</em> that are less than or equal to 1. So why is a value of 2 for j displayed? When <em>j</em> is 2, the value is displayed, after which the if statement is executed (which breaks out of the inner for loop). The outer for loop continues (the lone <code>print()</code> statement is there to add a line break in between increasing values of <em>i</em>), and <em>i</em> becomes 1. This occurs again until the outer for loop terminates (when <em>i</em> is 2).</p>
<p>Let’s now take a look at the binary search that was also covered in an earlier lesson. Recall that it is a very efficient search that requires a list to be sorted. Here’s the Python code that was developed in an earlier lesson:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>num <span class="op">=</span> <span class="bu">int</span>(<span class="bu">input</span>(<span class="st">"What integer would you like to search for? "</span>))</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>found <span class="op">=</span> <span class="va">False</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>first <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>last <span class="op">=</span> <span class="bu">len</span>(numbers) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="cf">while</span> (first <span class="op">&lt;=</span> last <span class="kw">and</span> found <span class="op">!=</span> <span class="va">True</span>):</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  mid <span class="op">=</span> (first <span class="op">+</span> last) <span class="op">//</span> <span class="dv">2</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (num <span class="op">==</span> numbers[mid]):</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    found <span class="op">=</span> <span class="va">True</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">elif</span> (num <span class="op">&gt;</span> numbers[mid]):</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    first <span class="op">=</span> mid <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span>:</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    last <span class="op">=</span> mid <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (found):</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="st">"</span><span class="sc">{}</span><span class="st"> was found at index </span><span class="sc">{}</span><span class="st">!"</span>.<span class="bu">format</span>(num, mid))</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="st">"</span><span class="sc">{}</span><span class="st"> was not found."</span>.<span class="bu">format</span>(num))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This version of the binary search keeps tracks of two boundaries (<em>first</em> and <em>last</em>) that identify the beginning and end indexes of the current portion of the list. Initially, <em>first</em> is 0 and <em>last</em> is <em>n</em>-1 (i.e., the entire list). If the middle value of the current portion of the list does not match the specified value, the appropriate half of the list is “discarded” by modifying either <em>first</em> (to discard the left half) or <em>last</em> (to discard the right half).</p>
<p>Recall that the binary search required a list to be sorted, thereby taking advantage of the algorithm’s efficiency improvement over the sequential search. Here’s the <strong>selection sort</strong> that was developed in an earlier lesson:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(numbers)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, n <span class="op">-</span> <span class="dv">1</span>):</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  minPosition <span class="op">=</span> i</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(i <span class="op">+</span> <span class="dv">1</span>, n):</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (numbers[j] <span class="op">&lt;</span> numbers[minPosition]):</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>      minPosition <span class="op">=</span> j</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  temp <span class="op">=</span> numbers[i]</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  numbers[i] <span class="op">=</span> numbers[minPosition]</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  numbers[minPosition] <span class="op">=</span> temp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Recall how the selection sort works: (1) the list is sorted from left to right; (2) at each pass (controlled by the outer for loop), the smallest value is swapped with the first item in the unsorted portion of the list; and (3) the inner for loop performs the comparison of every remaining item in the unsorted portion of the list to find the smallest value. For a review, see the lesson on <em>Searching and Sorting</em>.</p>
<p>There were two other sorting algorithms that were covered in earlier lessons: bubble sort and insertion sort. We never developed Python code for them. Let’s do this now. First, the bubble sort. Here is a version in pseudocode:</p>
<pre><code>for i ← 1..list length-1
  for j ← 1..list length-i
    if item j of list &lt; item j-1 of list
    then
      temp ← item j of list
      item j of list ← item j-1 of list
      item j-1 of list ← temp
    end
  next
next</code></pre>
<p>You may not have seen a for loop described in pseudocode before; however, this is a common way to accomplish this repetition construct in pseudocode. So what’s happening here? The basic idea is that a value in the list will be compared to the one before it. If they are out of order, then they are swapped. This continues, one index over (to the right), until the end of the list is reached. After the first pass, the largest value is guaranteed to be in its final position (i.e., at the end of the list). The next pass starts again at the beginning of the list; however, this time comparisons and swaps only take place until the second-to-last value in the list (because the last value has already been placed there during the last pass). Each time, the sorted list grows from right-to-left until the entire list is sorted.</p>
<p>The outer for loop controls the number of passes, while also providing a way to reduce the size of the unsorted portion of the list after each pass. It iterates from 1 through <em>n</em>-1. The inner loop controls the comparisons and swaps. Initially, the inner loop begins at 1 (the index of the second value in the list), and compares this value to the one before it (the first value in the list). If they are out of order, they are swapped. The swap works by using a variable (<em>temp</em>) that temporarily takes on one of the values in the list. This continues with the next index (i.e., 2), and so on. The last index compared is <em>n</em>-<em>i</em>. If the algorithms is in the first pass (i.e., <em>i</em> is 1) and the length of the list is 10, the last valid index in the list is <span class="math inline">\(10 – 1 = 9\)</span>.</p>
<p>Let’s take a look at what a Python version of the bubble sort looks like:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(<span class="bu">list</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, n):</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, n <span class="op">-</span> i <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="bu">list</span>[j] <span class="op">&lt;</span> <span class="bu">list</span>[j <span class="op">-</span> <span class="dv">1</span>]):</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>      temp <span class="op">=</span> <span class="bu">list</span>[j]</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">list</span>[j] <span class="op">=</span> <span class="bu">list</span>[j <span class="op">-</span> <span class="dv">1</span>]</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>      <span class="bu">list</span>[j <span class="op">-</span> <span class="dv">1</span>] <span class="op">=</span> temp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Recall that Python’s range function uses the first parameter as a lower bound and the second parameter as one above the upper bound. That is, it operates on the interval [<em>a</em>, <em>b</em>), where <em>a</em> is the (closed) lower bound and <em>b</em> is the (open) upper bound. Therefore, the upper bound of the outer loop is <em>n</em>: it iterates from 1 through (and including) <em>n</em>-1 as intended. Similarly, the upper bound of the inner loop is <em>n</em>-<em>i</em>+1: it iterates from 1 through (and including) <em>n</em>-<em>i</em> as intended. In the inner loop, if any value at an index is less than the value of the one before it, they are swapped.</p>
<p>Next, let’s take a look at the Python code for the insertion sort. Recall that the insertion sort works somewhat as you would arrange a hand of cards being dealt to you: a new card is inserted in its appropriate position in the hand of cards dealt so far.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a> <span class="dv">1</span>: i <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a> <span class="dv">2</span>: <span class="cf">while</span> (i <span class="op">&lt;</span> n):</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a> <span class="dv">3</span>:   <span class="cf">if</span> (<span class="bu">list</span>[i <span class="op">-</span> <span class="dv">1</span>] <span class="op">&gt;</span> <span class="bu">list</span>[i]):</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a> <span class="dv">4</span>:     temp <span class="op">=</span> <span class="bu">list</span>[i]</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a> <span class="dv">5</span>:     j <span class="op">=</span> i – <span class="dv">1</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a> <span class="dv">6</span>:     <span class="cf">while</span> (j <span class="op">&gt;=</span> <span class="dv">0</span> <span class="kw">and</span> <span class="bu">list</span>[j] <span class="op">&gt;</span> temp):</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a> <span class="dv">7</span>:       <span class="bu">list</span>[j <span class="op">+</span> <span class="dv">1</span>] <span class="op">=</span> <span class="bu">list</span>[j]</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a> <span class="dv">8</span>:       j <span class="op">-=</span> <span class="dv">1</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a> <span class="dv">9</span>:     <span class="bu">list</span>[j <span class="op">+</span> <span class="dv">1</span>] <span class="op">=</span> temp</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span>:   i <span class="op">+=</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Here’s an explanation of the code. Line 2 controls the number of passes through the list (<em>n</em>-1 total passes). The variable <em>i</em> is initialized to 1 (the second index in the list) and iterates through (but not including) <em>n</em>; therefore, through the last index in the list. So, starting with the second value in the list, it looks to the left (of this current value). Line 3 checks if that value is greater, and if so, then it must move it to the right. Line 4 temporarily stores the current item, and lines 5 and 6 then begin the process of iterating from the previous element, continuing to the left. At any point, if a value to the left is greater than the current item, it is shifted one index to the right. This continues either until (1) the beginning of the list is reached; or (2) a value that is not greater is found. Ultimately, the current item is placed into its proper position in the list. The outer loop then continues with the next value in the list (through the last value in the list).</p>
<p>Note that there are many other ways that the searches and sorts shown could have been implemented in Python. For example, the use of for loops in the selection sort could have been replaced with while loops (or vice versa in the insertion sort).</p>
</section>
<section id="other-operators" class="level2 page-columns page-full" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="other-operators"><span class="header-section-number">12</span> Other operators</h2>
<p>Python provides several more classes of operators than you are already familiar with. Recall that, so far, you have been exposed to (and should be quite familiar with) arithmetic operators, relational (comparison) operators, and assignment operators. In this lesson, we will cover several other classes of operators: <strong>logical operators</strong> and <strong>membership operators</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>logical operators</strong> evaluate two operands and return the logical result (i.e., True or False).</p>
</div>
</div>
<p>Think back to the primitive logic gates (<em>and</em>, <em>or</em>, and <em>not</em>). It turns out that they can be effectively mapped to conditions in if-statements. Logical operators operate on conditions (that use relational operators) and provide the overall logical result. In the following table, assume that <em>a</em> = True and <em>b</em> = False:</p>
<table class="table">
<caption>Python Logical Operators and Examples</caption>
<thead>
<tr class="header">
<th>Operator</th>
<th style="text-align: left;">Logical Equivalent</th>
<th style="text-align: left;">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>and</td>
<td style="text-align: left;">logical <em>and</em></td>
<td style="text-align: left;"><em>a</em> and <em>b</em> is False</td>
</tr>
<tr class="even">
<td>or</td>
<td style="text-align: left;">logical <em>or</em></td>
<td style="text-align: left;"><em>a</em> or <em>b</em> is True</td>
</tr>
<tr class="odd">
<td>not</td>
<td style="text-align: left;">logical <em>not</em></td>
<td style="text-align: left;">not <em>a</em> is False; not <em>b</em> is True</td>
</tr>
</tbody>
</table>
<p>Note that this is equivalent to the primitive logic gates, where 0 is substituted for False and 1 for True. Here is the truth table for the and gate shown in this manner:</p>
<table class="table">
<thead>
<tr class="header">
<th>A</th>
<th style="text-align: left;">B</th>
<th style="text-align: left;">A and B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>False</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
</tr>
<tr class="even">
<td>False</td>
<td style="text-align: left;">True</td>
<td style="text-align: left;">False</td>
</tr>
<tr class="odd">
<td>True</td>
<td style="text-align: left;">False</td>
<td style="text-align: left;">False</td>
</tr>
<tr class="even">
<td>True</td>
<td style="text-align: left;">True</td>
<td style="text-align: left;">True</td>
</tr>
</tbody>
</table>
<p>The logical operators sometimes make more sense when they are used in the context of a condition (e.g., in an if statement). Suppose that <em>a</em> = 5 and <em>b</em> = 10. The following condition would evaluate to False:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (a <span class="op">==</span> <span class="dv">5</span> <span class="kw">and</span> b <span class="op">&lt;</span> <span class="dv">10</span>):</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  ...</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Why? Clearly because, although <em>a</em> is equal to 5, <em>b</em> is not less than 10 (it’s equal to 10). Therefore, the <em>and</em> logical operator will return False if and only if both sides of the operator evaluate to True. In this case, the left side does while the right side does not. However, the following condition would evaluate to True:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (a <span class="op">==</span> <span class="dv">5</span> <span class="kw">or</span> b <span class="op">&lt;</span> <span class="dv">10</span>):</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  ...</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The <em>or</em> logical operator will return True if either (or both) sides of the operator evaluate to True. Since <em>a</em> is equal to 5, then the left side is True. In this case, the right side doesn’t need to be evaluated (and, in fact, it isn’t – more on that below).</p>
<p>The logical operators do work when the inputs (i.e., <em>a</em> and <em>b</em> in the previous examples) aren’t necessarily equal to True and False. That is, they also work when they are numeric values. Take, for example, the following statements:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span>: a <span class="op">=</span> <span class="dv">23</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span>: b <span class="op">=</span> <span class="dv">13</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="dv">14</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="dv">3</span>: <span class="bu">print</span>(a <span class="kw">and</span> b)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="dv">4</span>: <span class="bu">print</span>(a <span class="kw">or</span> b)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="dv">5</span>: <span class="bu">print</span>(<span class="kw">not</span> a)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="dv">6</span>: <span class="bu">print</span>(<span class="kw">not</span> b)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="dv">7</span>: a <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="dv">8</span>: <span class="bu">print</span>(<span class="kw">not</span> a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Here’s the output (with lines numbers matching those of the print statements above):</p>
<pre><code>3: 13
4: 23
5: False
6: False
8: True</code></pre>
<p>The output of lines 3 and 4 can be a bit confusing. Why, for example, is <em>a</em> <strong>and</strong> <em>b</em> 13? Or why is <em>a</em> <strong>or</strong> <em>b</em> 23? This can be explained by the following table, where the variables <em>a</em> and <em>b</em> have numeric values (as in the examples above):</p>
<table class="table">
<caption>Python Logical Operators and Examples</caption>
<thead>
<tr class="header">
<th>Operator</th>
<th style="text-align: left;">Logical Equivalent</th>
<th style="text-align: left;">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>and</td>
<td style="text-align: left;">logical <em>and</em></td>
<td style="text-align: left;">returns <em>a</em> if <em>a</em> is False, <em>b</em> otherwise</td>
</tr>
<tr class="even">
<td>or</td>
<td style="text-align: left;">logical <em>or</em></td>
<td style="text-align: left;">returns <em>b</em> if <em>a</em> is False, <em>a</em> otherwise</td>
</tr>
<tr class="odd">
<td>not</td>
<td style="text-align: left;">logical <em>not</em></td>
<td style="text-align: left;">returns False if <em>a</em> is True, True otherwise</td>
</tr>
</tbody>
</table>
<p>The output of lines 5, 6, and 8 makes sense when we realize that, in Python, 0 is False and any non-zero value is True! When <em>a</em> is 23 and <em>b</em> is 13, <em>a</em> evaluates to True (since it is non-zero); therefore, <strong>not</strong> <em>a</em> evaluates to False. This is the same with <em>b</em>. However, when <em>a</em> is 0, then it evaluates to False; therefore, <strong>not</strong> <em>a</em> evaluates to True. Formally, in the context of Boolean expressions, the following values are interpreted as false: False, None, numeric zero of all types, and empty strings and containers. All other values are interpreted as true.</p>

<div class="no-row-height column-margin column-container"><div class="callout callout-style-default callout-note callout-titled" title="Did you know">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Did you know
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <em>and</em> and <em>or</em> logical operators are <strong>short circuit</strong> operators. That is, to evaluate a True or False result, the minimum number of inputs required to produce such an output is evaluated. For example, suppose that <em>a</em> = False and <em>b</em> = True. The expression <em>a</em> <strong>and</strong> <em>b</em> is only True if both <em>a</em> and <em>b</em> are True. Since <em>a</em> is False, then there is no need to evaluate (or test) the value of <em>b</em>. This would be useless and waste CPU cycles. Similarly, if <em>a</em> = True and <em>b</em> = True, the evaluation of the expression <em>a</em> <strong>or</strong> <em>b</em> only requires checking that <em>a</em> is True for the entire expression to evaluate to True (i.e., there is no need to evaluate/test the value of b).</p>
</div>
</div></div><div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Membership operators</strong> test for some value’s membership in a sequence (e.g., to test if an element exists in a list, or if a character exists in a string).</p>
</div>
</div>
<p>In the following table, suppose that the Python list <em>numbers</em> = [ 1, 3, 5, 7, 9 ], <em>x</em> = 2, and <em>y</em> = 3.</p>
<table class="table">
<caption>Python Membership Operators and Examples</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 47%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Operator</th>
<th style="text-align: left;">Description</th>
<th style="text-align: left;">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>in</td>
<td style="text-align: left;">Returns True if a specified value is in a specified sequence or False otherwise</td>
<td style="text-align: left;"><em>x</em> in numbers is False; <em>y</em> in numbers is True</td>
</tr>
<tr class="even">
<td>not in</td>
<td style="text-align: left;">Returns True if a specified value is not in a specified sequence or False otherwise</td>
<td style="text-align: left;"><em>x</em> not in numbers is True; <em>y</em> not in numbers is False</td>
</tr>
</tbody>
</table>
<p>You have seen this in previous for loop examples (e.g., <code>for i in list</code>). This for loop configuration has the variable <em>i</em> take on each of the values in <em>list</em>, one at a time</p>
</section>
<section id="string-methods" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="string-methods"><span class="header-section-number">13</span> String methods</h2>
<p>Strings are often necessary when writing programs. As such, Python provides a variety of methods that work on strings. You have already seen one such method, <strong>format()</strong>, that formats a string as specified (we did this earlier in one variant of the <strong>print</strong> statement). The following table lists some of the more useful string methods:</p>
<table class="table">
<caption>Python String Methods/Functions</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 81%">
</colgroup>
<thead>
<tr class="header">
<th>Operation</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>str.capitalize()</code></td>
<td style="text-align: left;">capitalizes the first character of a string</td>
</tr>
<tr class="even">
<td><code>str.find()</code></td>
<td style="text-align: left;">returns the first index of a string within another string</td>
</tr>
<tr class="odd">
<td><code>str.format()</code></td>
<td style="text-align: left;">formats a string according to a specification</td>
</tr>
<tr class="even">
<td><code>str.isdigit()</code></td>
<td style="text-align: left;">determines if a string consists only of numeric characters</td>
</tr>
<tr class="odd">
<td><code>str.lower()</code></td>
<td style="text-align: left;">converts a string to lowercase</td>
</tr>
<tr class="even">
<td><code>str.replace()</code></td>
<td style="text-align: left;">replaces all occurrences of a string (within a string) with another string</td>
</tr>
<tr class="odd">
<td><code>str.split()</code></td>
<td style="text-align: left;">returns a list of the words in a string</td>
</tr>
<tr class="even">
<td><code>str.upper()</code></td>
<td style="text-align: left;">converts a string to uppercase</td>
</tr>
</tbody>
</table>
<p>These string methods are explained in greater detail in a variety of online sources. We suggest that you Google them and try them out. However, here are a few examples in IDLE:</p>
<pre><code>&gt;&gt;&gt; s = "So, when is this going to get difficult?"
&gt;&gt;&gt; s
'So, when is this going to get difficult?'
&gt;&gt;&gt; s.capitalize()
'So, when is this going to get difficult?'
&gt;&gt;&gt; s.find("going")
17
&gt;&gt;&gt; s.isdigit()
False
&gt;&gt;&gt; s.lower()
'so, when is this going to get difficult?'
&gt;&gt;&gt; s.upper()
'SO, WHEN IS THIS GOING TO GET DIFFICULT?'
&gt;&gt;&gt; s.replace("difficult", "easy")
'So, when is this going to get easy?'
&gt;&gt;&gt; s.split()
['So,', 'when', 'is', 'this', 'going', 'to', 'get', 'difficult?']
&gt;&gt;&gt; s.split("i")
['So, when ', 's th', 's go', 'ng to get d', 'ff', 'cult?']</code></pre>
<p>Note the execution of the string method <strong>str.find()</strong> above: <code>s.find("going")</code>. This string method returns the first index of the string, “going”, within the string, <em>s</em>. Why is the result 17? At first glance, it seems that the first character of the string, “going”, is at position 18. However, strings are sequences (just like lists); therefore, the characters of a string in Python begin at index 0.</p>
</section>
<section id="importing-extertan-libraries" class="level2" data-number="14">
<h2 data-number="14" class="anchored" data-anchor-id="importing-extertan-libraries"><span class="header-section-number">14</span> Importing extertan libraries</h2>
<p>It is often useful (and necessary) to import external functionality into our programs. In fact, you’ve seen (and used) this before (in the lesson <em>Introduction to Data Structures</em>), although it may not have been explained in detail. Often, others have designed functions and other bits of code that may prove useful. We don’t always want to recreate things that already exist. Python supports the importing of such things via the <strong>import</strong> reserved word. For example, many of the programs we create require the use of mathematical functions beyond simple arithmetic (e.g., sin, cos, tan) or mathematical constants (e.g., pi, e). The structure of an import statement is as follows:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> library</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Pretty simple. Here’s an example of the importing and use of the math library:</p>
<pre><code>&gt;&gt;&gt; pi
Traceback (most recent call last):
  File "&lt;pyshell#0&gt;", line 1, in &lt;module&gt;
    pi
NameError: name 'pi' is not defined
&gt;&gt;&gt; import math
&gt;&gt;&gt; math.pi
3.141592653589793
&gt;&gt;&gt; math.e
2.718281828459045
&gt;&gt;&gt; math.sin(math.pi)
1.2246467991473532e-16
&gt;&gt;&gt; math.cos(math.pi)
-1.0
&gt;&gt;&gt; math.log(1000)
6.907755278982137
&gt;&gt;&gt; math.log(math.e)
1.0</code></pre>
<p>Note in the example, the invalid use of <em>pi</em> before importing that math library. In addition, any value or function used in a library must be fully qualified with the name of the library (e.g., we need to specify <em>math.pi</em> and not just <em>pi</em>). Alternatively, we can itemize what we wish to import from a library. This allows us to use values and functions directly without having to specify the library name. The structure of such an import statement is as follows:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> library <span class="im">import</span> function <span class="co"># (or constant)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>For example, the constant PI and the sin() function can be formally imported as follows:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> math <span class="im">import</span> pi, sin</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Moreover, these can be directly used as follows:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pi)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sin(pi))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Here’s the output:</p>
<pre><code>3.141592653589793
1.2246467991473532e-16</code></pre>
<p>Formally, Python calls its libraries <strong>modules</strong>. And we can even write our own modules! They are just Python programs that typically provide definitions of constants and functions that other Python programs import and make use of. Python modules just need to be saved as a .py file and located in the same folder/directory as a Python program that needs to make use of it. For example, we could include several useful functions in a file called MyGoodies.py. Suppose that it contained the following:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> time <span class="im">import</span> time</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># starts a timer</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> start_time():</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="kw">global</span> start</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  start <span class="op">=</span> time()</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="co"># stops the timer and returns the time elapsed</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> stop_time():</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  stop <span class="op">=</span> time()</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>  elapsed <span class="op">=</span> stop <span class="op">-</span> start</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> elapsed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The purpose of this example module is to use it to time how long algorithms take to execute. It’s quite simple. The function <em>start_time</em> effectively starts a timer (through the time library’s <em>time</em> function) by capturing the current “time” – which is essentially the number of seconds elapsed since an epoch defined in your operating system. For Unix and Unix-like operating systems (e.g., the “flavor” of Linux used on the Raspberry Pi), the epoch is 1970-01-01 00:00:00. The function <em>stop_time</em> captures the current time again (this time, after the algorithm has finished), and calculates and returns the difference between the two.</p>
<p>We can make use of this module as follows:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> MyGoodies <span class="im">import</span> start_time, stop_time</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="co"># start a timer</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>start_time()</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a><span class="co"># do something that takes a little time</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">100000000</span>):</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">pass</span></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="co"># stop the timer</span></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a><span class="dv">18</span></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>duration <span class="op">=</span> stop_time()</span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a><span class="co"># display how long it took</span></span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Algorithm took </span><span class="sc">{}</span><span class="st"> seconds."</span>.<span class="bu">format</span>(duration))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Note that the “algorithm” in the test code above really does nothing. It’s just there to take up some noticeable amount of time so that the module can be tested. Here’s a sample run:</p>
<pre><code>jgourd@pi:~$ python MyGoodiesTest.py 
Algorithm took 5.71634602547 seconds.</code></pre>
</section>
<section id="programming-languages" class="level2" data-number="15">
<h2 data-number="15" class="anchored" data-anchor-id="programming-languages"><span class="header-section-number">15</span> Programming Languages</h2>
<p>The kinds of languages that are widely used today are known as programming languages. Programming languages allow us to represent algorithms in a way that is similar to English but is more structured and much less ambiguous.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>programming language</strong> is a precisely constructed language that is specifically used to communicate instructions to a computer.</p>
</div>
</div>
<p>English is a spoken language. As such, it was spoken first, rules were later defined and written down. Therefore, there are many exceptions (i.e., words and phrases that are grammatically correct but don’t conform to the general grammar/spelling rules). Spoken languages are sometimes ambiguous and open to interpretation. This means that a single statement can have multiple meanings. For example, the statement “I made the robot fast” can mean several different things. Does it mean that the robot was built quickly? Or does it mean that the robot was modified so that it would move around more quickly than it did before? Perhaps it means that the robot is named Fast. Or maybe that we managed to make the robot stop eating nuts and bolts.</p>
<p>Humans rely on external factors like context and body language to understand the true meaning of a statement in a spoken language. And even then mistakes in interpretation still happen. With computers however, we need a language that is so structured and unambiguous that every computer can understand and interpret a given statement in the exact same way. For example, we don’t want two different computers giving us two completely different answers to the arithmetic expression <span class="math inline">\(1 + 1\)</span>. In contrast to spoken languages, programming languages are first defined with rules. The language itself is then derived from those rules. Programming languages are therefore quite structured and not ambiguous. They are very precise and logical.</p>
<p>There are many different programming languages that can be used to describe an algorithm. One of them, for example, is called Python, and it is what we will be using for the majority of the Living with Cyber curriculum. It is the duty of the programmer to write down the tasks that he/she wants done in a given programming language. Since computers can only understand machine language, we utilize an application known as a compiler that translates this programming language into machine language.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>compiler</strong> is a tool used to translate an algorithm expressed in a programming language to machine language. The process by which this conversion from programming language to machine language is done is called <strong>compilation</strong>.</p>
</div>
</div>
<p>The compilation process takes an algorithm written in a programming language and translates it to assembly language. From there, a process known as linking converts the assembly language to machine language. This is illustrated by <a href="#fig-compilation" class="quarto-xref">Figure&nbsp;1</a> below:</p>
<div id="fig-compilation" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-compilation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Lesson04-01.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-compilation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The compilation process
</figcaption>
</figure>
</div>
<p>Once machine language is generated to match a program, the computer can then directly execute the program and implement the algorithm. A fully compiled language is only executable by a CPU with the same characteristics and operating system (often, including version) as that which it was compiled for. A programmer who wants wide distribution of his software will need to compile source code to the various destination computing architectures and operating systems that are the most likely to be used by the target audience for the application. Of course, the programmer could simply distribute source code and let users compile that themselves. Often, however, programmers do not wish to distribute source code for a variety of reasons (e.g., intellectual property). <a href="#fig-compilation2" class="quarto-xref">Figure&nbsp;2</a> below shows how a program would need to be compiled numerous times to cover a range of target computing architectures and operating systems:</p>
<div id="fig-compilation2" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-compilation2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Lesson04-02.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-compilation2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The compilation process needs to be done for different target architectures
</figcaption>
</figure>
</div>
<p>Not all programming languages are compiled to machine language. Some are never compiled and are executed, one instruction at a time, by an <strong>interpreter</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>An <strong>interpreter</strong> is a tool used to evaluate instructions, written in a programming language, as the program is executed.</p>
</div>
</div>
<p>An interpreter can be thought of as a real time compiler that executes high level programming language instructions, one at a time. Interpreted languages are much slower to execute than compiled languages. Examples of interpreted languages are Python, PHP, JavaScript, and Perl. To execute a program written in an interpreted language, you must have an appropriate interpreter installed on your computing system. Interpreted languages also require programmers to distribute their source code, and users to have an appropriate interpreter installed on their system. Maintaining code privacy is therefore not possible with interpreted languages.</p>
<p>Partially compiled and interpreted languages combine the convenience of interpreted languages (i.e., not having to compile source code to a large number of target machine language executables) and the privacy and speed of compiled languages (i.e., not having to distribute source code).</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>hybrid language</strong> is a programming language that is compiled down to an intermediate language, and then interpreted (while the program is executed) from there.</p>
</div>
</div>
<p>Examples of partially compiled languages are Java, Python, and Lisp. Note that Python can be strictly interpreted or partially compiled depending on the programmer’s preferences. The intermediate language is distributed and subsequently executed on any computing platform that has an interpreter for the intermediate language. For example, Java source code is typically expressed in a <em>.java</em> file and partially compiled to Java bytecodes (in a <em>.class</em> file) that can then be distributed. A Java Virtual Machine (JVM) executes the bytecodes by interpreting each instruction, one at a time. The benefit of this method is that a programmer can distribute a single file to everyone, regardless of CPU architecture and operating system. Anyone wanting to execute the file simply needs to have a version of the JVM for their computing system. This is illustrated in <a href="#fig-compilation3" class="quarto-xref">Figure&nbsp;3</a> below:</p>
<div id="fig-compilation3" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-compilation3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Lesson04-03.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-compilation3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Partially compiled languages
</figcaption>
</figure>
</div>
</section>
<section id="programming-paradigms" class="level2" data-number="16">
<h2 data-number="16" class="anchored" data-anchor-id="programming-paradigms"><span class="header-section-number">16</span> Programming Paradigms</h2>
<p>Over the past forty years or so, three general classes, or paradigms, of programming languages have emerged. These paradigms include the imperative paradigm, the functional paradigm, and the logical paradigm. In addition, during the past decade or so these paradigms have been extended to include object-oriented features. A language is classified as belonging to a particular paradigm based on the programming features it supports.</p>
<p>Object-oriented imperative languages are, by far, the most popular type of programming language. Both Java and C++ (two of the most used programming languages in industry) are object-oriented imperative languages. Scratch and Python are imperative languages – although Python does contains object- oriented attributes, Scratch does not.</p>
<p>The imperative paradigm is based on the idea that a program is a sequence of commands or instructions (usually called statements) that the computer is to follow to complete a task. The imperative style of programming is the oldest, and now with object-oriented extensions, continues to be far and away the most popular style of programming.</p>
<p>The Living with Cyber curriculum first (and very briefly) utilizes Scratch as the programming language. This is quickly followed by Python. Scratch is not intended to be used to create applications designed for production systems. That is, it is not a general purpose programming language. Instead, it is a teaching tool aimed at simplifying the process of learning to program. Scratch purposefully omits many features available in other popular programming languages in order to keep the language from becoming overly complex. This allows you to focus on the big picture rather than get bogged down in the complexities inherent in real programming languages and their development environments.</p>
<p>One way of thinking about writing Scratch programs is to compare it to programming in a production programming language with training wheels on. Complex and useful programs can be written in Scratch; however, there are many things that programmers are allowed to do in production languages that are not possible (at least not straightforward) in Scratch. For example, Scratch does not support functions and function calls directly, nor does it support recursion directly. These terms may not be familiar right now; however, these restrictions are designed to help beginning programmers avoid making common mistakes.</p>
<p>General purpose programming languages are more robust, and can (and are) used in more situations than educational programming languages like Scratch. Think of it like this: using a programming language like Scratch is like building a Lego house only using 2x4 Lego pieces. While it is possible to do so, there is a limitation on what kinds of houses you can build. Conversely, using more general purpose programming languages is like building a house with any kind of Lego piece you can think up in your mind. There are fewer limitations, and the kinds of houses that you can build are limitless. From this point, we will use Python as the general purpose programming language in the course.</p>
</section>
<section id="why-python" class="level2 page-columns page-full" data-number="17">
<h2 data-number="17" class="anchored" data-anchor-id="why-python"><span class="header-section-number">17</span> Why Python?</h2>
<p>You may have heard about other general purpose programming languages: Java, C, C++, C#, Visual Basic, and so on. So why use Python instead of, say, Java? In the end, it amounts to the simple idea that, unlike all of the other general purpose programming languages listed above, Python allows us to create powerful programs with limited knowledge about syntax, therefore allowing us to focus on problem solving instead. In a sense, Python is logical. That is, nothing must be initially taken on faith (that will ostensibly be explained at a later time). There isn’t any excess baggage that’s required in order to begin to write even simple Python programs.</p>
<p>Recall how, in geometry, the formula for calculating the volume of a cone was given. At that time, it was simply inexplicable. That is, you were most likely told to memorize it. It is not until a calculus course that this formula is actually derived, and how it came to be is fully explained. Why? Well, it is simply because it requires calculus in order to do so. Most students taking a geometry course have not yet had calculus; however, formulas for calculating the volume of various objects (including a cone) are typical in such a course. The problem, of course, is that we are told to take it on faith that it, in fact, works as described. We are told that, how it works and how it was derived, will be explained at a later time. The problem with this is that it forces memorization of important material as opposed to a deep understanding of it (which, in the end, is the goal).</p>
<p>A similar thing actually occurs in a lot of programming languages. Often, we must memorize syntax that will be explained later. Python is unique in that it does a pretty good job of taking all of that out by just being simple. Programming in Python is immediately logical and explicable.</p>
<p>Take the following simple example of a program that displays the text, “Programming rules, man!” in various general purpose programming languages:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode java code-with-copy"><code class="sourceCode java"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">// Basic text display program in Java.</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="kw">public</span> <span class="kw">class</span> SimpleProgram</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="op">{</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">public</span> <span class="dt">static</span> <span class="dt">void</span> <span class="fu">main</span><span class="op">(</span><span class="bu">String</span><span class="op">[]</span> args<span class="op">)</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>    <span class="op">{</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>        <span class="bu">System</span><span class="op">.</span><span class="fu">out</span><span class="op">.</span><span class="fu">println</span><span class="op">(</span><span class="st">"Programming rules, man!"</span><span class="op">);</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb54"><pre class="sourceCode c code-with-copy"><code class="sourceCode c"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">// Basic text display program in C</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="pp">#include </span><span class="im">&lt;stdio.h&gt;</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="dt">int</span> main<span class="op">()</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="op">{</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>    printf<span class="op">(</span><span class="st">"Programming rules, man!</span><span class="sc">\n</span><span class="st">"</span><span class="op">);</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb55"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">// Basic text display program in C++</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="pp">#include </span><span class="im">&lt;iostream&gt;</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="kw">using</span> <span class="kw">namespace</span> std<span class="op">;</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="dt">int</span> main<span class="op">()</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="op">{</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"Programming rules, man!"</span> <span class="op">&lt;&lt;</span> endl<span class="op">;</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb56"><pre class="sourceCode cs code-with-copy"><code class="sourceCode cs"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">//Basic text display program in C#</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="kw">public</span> <span class="kw">class</span> SimpleProgram</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="op">{</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">public</span> <span class="kw">static</span> <span class="dt">void</span> <span class="fu">Main</span><span class="op">()</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    <span class="op">{</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>        System<span class="op">.</span><span class="fu">Console</span><span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span><span class="st">"Programming rules, man!"</span><span class="op">);</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb57"><pre class="sourceCode vb code-with-copy"><code class="sourceCode monobasic"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">'Basic text display program in Visual Basic</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="kw">Module </span>Hello</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">Sub </span>Main()</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>        MsgBox(<span class="st">"Programming rules, man!"</span>)</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">End Sub</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="kw">End Module</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>And in Python</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Programming rules, man!"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>In all of these examples, compiling and running the programs (or interpreting them) produces a single line of output text: “Programming rules, man!” Did you notice that, in all of the examples (except for Python), there seems to be a good bit of seemingly extra stuff for such a simple program? There are a lot of words that you may not be familiar with or immediately understand: <em>class, public, static, void, main/Main, #include, printf, cout, namespace, String[], endl, Module, Sub, MsgBox,</em> and so on. In fact, the only readable version to a beginner is usually the one written in Python. It is pretty evident that the statement <em>print(“Programming rules, man!”)</em> means to display that string of characters to the screen (or console).</p>
<p>Python is extremely readable because it has very simple and consistent syntax. This makes it perfect for beginner programmers. It also forces good coding practices and style, something that is very important for beginners (especially when it comes to debugging and/or maintaining programs). Python has a large set of libraries that provide powerful functionality to do just about anything. Libraries allow Python programmers to use all kinds of things that others have created (i.e., we don’t have to reinvent the wheel). A huge benefit of Python is that it is platform independent. It doesn’t matter what operating system you use, it is supported with minimal setup and configuration, and there is no need to deal with dependencies (i.e., other things that are required in order to just begin to code in Python).</p>
<p>Don’t think that, because of its simplicity, Python is therefore not a powerful language (or perhaps that it doesn’t compete with Java or C++). Python is indeed powerful, and can do everything that other programming languages can do (e.g., it does support the object-oriented paradigm). It is based on a few profound ideas (collectively known as <a href="https://peps.python.org/pep-0020/">The Zen of Python</a> written by Tim Peters)</p>

<div class="no-row-height column-margin column-container"><div class="callout callout-style-default callout-note callout-titled" title="Did you know">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Did you know
</div>
</div>
<div class="callout-body-container callout-body">
<p>The name of the Python programming language is taken from a television series called <em>Monty Python’s Flying Circus</em> (and not from the snake).</p>
</div>
</div></div></section>
<section id="integrated-development-environments-ides" class="level2 page-columns page-full" data-number="18">
<h2 data-number="18" class="anchored" data-anchor-id="integrated-development-environments-ides"><span class="header-section-number">18</span> Integrated Development Environments (IDEs)</h2>
<p>Many programmers write their programs in a general purpose programming language using nothing but a text-based editor (usually a simplistic one, albeit with useful characteristics such as syntax highlighting). In fact, some write programs at the command line (in the terminal) using nothing but a text-based text editor (i.e., without graphical characteristics). Most programmers, however, use an IDE (Integrated Development Environment).</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>An <strong>Integrated Development Environment (IDE)</strong> is a piece of software that allows computer programmers to design, execute, and debug computer programs in an integrated and flexible manner.</p>
</div>
</div>
<p>On the Raspberry Pi, the IDE used to design Python programs is called IDLE (which stands for Python’s <strong>I</strong>ntegrated <strong>D</strong>eve<strong>L</strong>opment <strong>E</strong>nvironment). Other IDEs exist for pretty much all of the most used general purpose programming languages: Eclipse, Visual Studio, Code::Blocks, NetBeans, Dev-C++, Xcode, and so on. In fact, many of these IDEs support more than one language (some natively, others by installing additional plug-ins or modules)! Here’s an image of IDLE with the program shown earlier implemented (and executed):</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Lesson04-04.png" class="img-fluid figure-img"></p>
<figcaption>IDLE shell with simple python statement</figcaption>
</figure>
</div>
<p>On the Raspberry Pi, IDLE can be launched as follows:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Lesson04-05.png" class="img-fluid figure-img"></p>
<figcaption>Launching IDLE on the raspberry pi</figcaption>
</figure>
</div>
<p>Python programs can also be created and executed at the command line (or terminal). We do so by launching a terminal and typing <strong>python</strong>, which brings up the Python shell:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Lesson04-06.png" class="img-fluid figure-img"></p>
<figcaption>Launching IDLE in the terminal</figcaption>
</figure>
</div>

<div class="no-row-height column-margin column-container"><div class="callout callout-style-default callout-note callout-titled" title="Did you know">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Did you know
</div>
</div>
<div class="callout-body-container callout-body">
<p>On computers that have two alternate versions of python installed on them, you might have to type <strong>python3</strong> as the command to open up a python shell like the one in the image.</p>
</div>
</div></div></section>
<section id="scratch-vs.-python" class="level2" data-number="19">
<h2 data-number="19" class="anchored" data-anchor-id="scratch-vs.-python"><span class="header-section-number">19</span> Scratch vs.&nbsp;Python</h2>
<p>Earlier in this lesson, you learned that programs written in a programming language are either compiled (to machine language so that a computer can execute them directly) or interpreted, statement-by-statement (in a sense, you could say that programs written in interpreted languages are compiled, line-by-line, in real time). Python is an interpreted language that implements the imperative paradigm. That is, programs are designed as a sequence of instructions (called statements) that can be followed to complete a task.</p>
<p>Let’s take a look at a simple program in Scratch and see how it compares to the same thing in Python:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Lesson04-07.png" class="img-fluid figure-img"></p>
<figcaption>Basic Loop structure in Scratch</figcaption>
</figure>
</div>
<p>What does this program do? Simply put, it displays the numbers 2, 4, 6, and 8. Take a look at the script above. The variable <em>n</em> is initially set to 1. A <em>repeat-until</em> loop is executed so long as <em>n</em> is less than 10 (i.e., 1 through 9). Each time the body of the loop is executed, the string “n is now (plus the value of n)” is displayed if <em>n</em> is evenly divisible by 2. For example, if <em>n</em> is 4, then the string <strong>n is now 4</strong> is displayed. Recall that the <em>mod</em> operator returns the remainder of a division. Therefore, when <strong>n mod 2 = 0</strong> is true, it means that the remainder of <em>n</em> divided by 2 is zero – so <em>n</em> must be even! At the end of the body of the loop, the variable <em>n</em> is incremented (ensuring that <em>n</em> will eventually reach the value 10, and we will break out of the <em>repeat-until</em> loop).</p>
<p>Here’s how this can be similarly done in Python:</p>
<div id="0a1a5894" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="cf">while</span> n <span class="op">&lt;</span> <span class="dv">10</span>:</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> n <span class="op">%</span> <span class="dv">2</span> <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"n is now "</span> <span class="op">+</span> <span class="bu">str</span>(n))</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> n <span class="op">+</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>n is now 2
n is now 4
n is now 6
n is now 8</code></pre>
</div>
</div>
<p>At this point, it is fine if you don’t understand everything that’s going on syntactically. The idea is simply to illustrate how Scratch and Python differ (and are similar!). But let’s try to explain.</p>
<ul>
<li><p>The block, <em>set n to 1</em>, in Scratch is implemented in Python as, <code>n = 1</code>. Pretty similar!</p></li>
<li><p>Python has no <em>repeat-until</em> repetition construct. Instead, we can use a <em>while</em> construct with a modified condition. Repeating a task until a variable (in this case, <em>n</em>) is 10 is the same thing as repeating it while the variable is less than 10.</p></li>
<li><p>If-statements are similar; however, the <em>mod</em> and <em>equality</em> operators differ. In Python, we check for equality using the double-equal (==) operator. The mod operator is a percent sign (%). So the block, <em>if n mod 2 = 0</em>, in Scratch can be implemented in Python as, <code>if n % 2 ==   0</code>.</p></li>
<li><p>Generating the output, “n is now 4,” for example, can be implemented in Scratch using the familiar print statement: <code>print ("n is now 4")</code>. Of course, we don’t always want to display the literal string “n is 4”. So we concatenate (or join) the value of <em>n</em> to the string “n is now” just as we did in Scratch. However, since <em>n</em> is not a string of characters (i.e., it is a number – an integer to be precise), then it must first be converted to a string before being concatenated to another string. This is what <code>str(n)</code> does.</p></li>
<li><p>Finally, the value of <em>n</em> is incremented by 1 with the statement <em>n = n + 1</em>.</p></li>
</ul>
<p>In Scratch, it is easy to see the blocks that belong in the body of a repetition construct. The puzzle pieces intrinsically capture this (i.e., they are quite literally visible inside the <em>repeat-until</em> block in the script above). In Python, we denote statement hierarchy (i.e., if statements belong in the body of a construct such as a <em>while</em> loop) by using <strong>indentation</strong>. Note how it is quite clear which statements belong in the body of the <em>while</em> loop above: the if-statement and the statement that increments the variable <em>n</em> by 1. Note that the <em>print</em> statement is inside the true part of the if-statement (this is evident by how it is directly beneath the if-statement and indented further to the right). Again, at this point it is fine to have a minimal grasp of Python’s syntax.</p>
</section>
<section id="python-primer" class="level2 page-columns page-full" data-number="20">
<h2 data-number="20" class="anchored" data-anchor-id="python-primer"><span class="header-section-number">20</span> Python Primer</h2>
<div class="callout callout-style-default callout-important callout-titled" title="Activity">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Activity
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Open your IDE of choice (e.g.&nbsp;IDLE) and follow along with the professor as they try out different code snippets in the python shell. This activity should give you an idea of</p>
<ul>
<li><p>the kinds of operators and expressions that are possible in the python shell.</p></li>
<li><p>how to execute print statements consisting of different kinds of data</p></li>
<li><p>how to prompt the user for some input in the middle of code execution</p></li>
<li><p>storing values in variables</p></li>
<li><p>using variables and the values stored within as part of other expressions.</p></li>
</ul>
</div>
</div>
</div>
<p>You should be able to understand every single statement in the snippet below and even create a similar sequence on your own with a clear grasp of what each statement is doing.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>a <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> <span class="dv">15</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>a<span class="sc">}</span><span class="ss"> ^ </span><span class="sc">{</span>b<span class="sc">}</span><span class="ss"> = </span><span class="sc">{</span>a<span class="op">**</span>b<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(a <span class="op">+</span> <span class="dv">6</span>)</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>c <span class="op">=</span> <span class="bu">input</span>(<span class="st">"What is your name?"</span>)</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Hello </span><span class="sc">{</span>c<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> <span class="bu">input</span>(<span class="ss">f"so </span><span class="sc">{</span>c<span class="sc">}</span><span class="ss">, How old are you?"</span>)</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>e <span class="op">=</span> <span class="bu">int</span>(d)</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"You are </span><span class="sc">{</span>e<span class="sc">}</span><span class="ss"> years old and you will be 100 in </span><span class="sc">{</span><span class="dv">100</span><span class="op">-</span>e<span class="sc">}</span><span class="ss"> years"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<section id="creating-programs-and-saving-files" class="level3 page-columns page-full" data-number="20.1">
<h3 data-number="20.1" class="anchored" data-anchor-id="creating-programs-and-saving-files"><span class="header-section-number">20.1</span> Creating Programs and Saving Files</h3>
<p>So far, we have been entering statements in the Python shell. These statements have been interpreted, one at a time. If we were to close the Python shell, everything that we entered would be lost. In order to save Python programs, we must type them in a separate editor outside of the Python shell, save them in a file. Once this has been done, we can then execute them in the Python shell.</p>
<p>To create a new Python program, click on <strong>File | New File</strong> (or press <strong>Ctrl+N</strong>) in the Python shell. This brings up a new window (an editor that is a part of IDLE) in which we can type our program. Type the following program into this new window:</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>a <span class="op">=</span> <span class="bu">int</span>(<span class="bu">input</span>(<span class="st">"Enter a number: "</span>))</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> <span class="bu">int</span>(<span class="bu">input</span>(<span class="st">"Enter another number: "</span>))</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>a<span class="sc">}</span><span class="ss"> raised to the power </span><span class="sc">{</span>b<span class="sc">}</span><span class="ss"> is </span><span class="sc">{</span>a<span class="op">**</span>b<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>If you are using IDLE, this is what your window should look like.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Lesson04-08.png" class="img-fluid figure-img"></p>
<figcaption>Basic python file in IDLE</figcaption>
</figure>
</div>

<div class="no-row-height column-margin column-container"><div class="callout callout-style-default callout-note callout-titled" title="Did you know">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Did you know
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note that when editing a python file, there will NOT be any <strong>&gt;&gt;&gt;</strong> symbols on the left of your lines of code. If you see those symbols, that means you are still within the shell and not in an actual python file.</p>
</div>
</div></div><p>Before we can run this program, it must be saved. Do so by clicking on <strong>File | Save</strong> (or press <strong>Ctrl+S</strong>). Give it an appropriate name, and save it to an appropriate location. Now it can be executed by clicking on <strong>Run | Run Module</strong> (or by pressing <strong>F5</strong>). This executes the program in the Python shell:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Lesson04-09.png" class="img-fluid figure-img"></p>
<figcaption>Code output when python file is run</figcaption>
</figure>
</div>
<p>You can run your code any number of times by selecting <strong>Run | Run Module</strong> (or pressing F5). If your code requires some input from the user, each execution affords you an opportunity to try out different input options e.g.&nbsp;inputing different numbers to see what one raised to another is.</p>
</section>
<section id="reloading-a-saved-file" class="level3" data-number="20.2">
<h3 data-number="20.2" class="anchored" data-anchor-id="reloading-a-saved-file"><span class="header-section-number">20.2</span> Reloading a saved file</h3>
<p>To load a saved Python program, simply double-click on the saved file. This should bring up the <strong>IDLE</strong> editor with your file loaded in it. Sometimes, double-clicking on the file just opens it up in a notepad- like editor by default. To force it to open in IDLE, right-click the file instead, and select <strong>Open with IDLE</strong>.</p>
<p>The program can then be executed as before, by clicking on <strong>Run | Run Module</strong> (or by pressing F5). This will automatically open a Python shell and execute the program.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Activity">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Activity
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Write a python program that prompts the user for two numbers and displays the quotient and remainder when the first number is divided by the second. As an example, if the user typed in 17 and 3 for the first and second number respectively, it would output a result similar to the one shown below.</p>
<div id="14c82d31" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>The quotient of 17 divided by 3 is 5 with a remainder of 2</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="data-types-constants-and-variables-1" class="level3" data-number="20.3">
<h3 data-number="20.3" class="anchored" data-anchor-id="data-types-constants-and-variables-1"><span class="header-section-number">20.3</span> Data types, constants, and variables</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>The kinds of values that can be expressed in a programming language are known as its <strong>data types</strong></p>
</div>
</div>
<p>Recall that Scratch supports only two data types: text and numbers. Since Python is a general purpose programming language, it supports many more data types. Actually, it can support virtually any type that you can think of! That is, Python allows you to define your own type for use in whatever way you wish. Since this is user-defined, let’s focus on what are called primitive types for now.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>primitive types</strong> of a programming language are those data types that are built-in (or standard) to the language and typically considered as basic building blocks (i.e., more complex types can be created from these primitive types).</p>
</div>
</div>
<p>Python’s standard types can be grouped into several classes: numeric types, sequences, sets, and mappings. Although there are actually others, we will focus on these in the <em>Living with Cyber</em> curriculum.</p>
<p>Numeric types include whole numbers, floating point numbers, and complex numbers. Python has two whole number types: <code>int</code> and <code>long</code>. The <code>int</code> data type is a 64-bit integer. This means that 64 bits (i.e.&nbsp;a bit can be either 0 or 1) is used to represent a single whole number. For example the following series of bits represent a single integer (in fact it represents the number 846,251,337): 0000 0000 0000 0000 0000 0000 0000 0000 0011 0010 0111 0000 1100 0101 0100 1001. We will explore this in more detail at a later time. The <code>long</code> data type is an integer of unlimited length. This means Python will give us enough bits to store any number we want! Note that in Python 3.x, an <code>int</code> is an integer of unlimited length (there is no long data type). These integer types can represent negative or positive whole numbers. The <code>float</code> type is a 64-bit floating point (decimal) number. This means it can hold numbers like 3.14 and -90.3324235. Lastly, the <code>complex</code> type represents complex numbers (i.e., numbers with real and imaginary parts). Most of our programs will require only <code>int</code> and <code>float</code>.</p>
<p>So what does this all mean? We create variables that contain data of some data type. Knowing the data type of a variable is like knowing the superpowers of a person you can control. In this analogy, the superpowers of a data type are the methods and properties that can be leveraged for use in whatever program you are writing at the time. For example, one of the superpowers of the numeric data types is raising them to a power. To do that, we can use the function of the form <code>pow(x,y)</code>. In this example, <em>x</em> and <em>y</em> are variables that are of type <code>int</code> or <code>float</code>. The <strong>pow</strong> function returns the value of the computation involving raising the value in x to the power of the value in y (i.e., x<sup>y</sup> ). This function would not typically be able to work for variables that aren’t numeric data types. You may recall that the same functionality can be implemented in Python as: <code>x ** y</code>. This effectively performs the same thing.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>constant</strong> is defined as a value of a particular type that does not change over time.</p>
</div>
</div>
<p>In Python (just as in Scratch), both numbers and text may be expressed as constants. <strong>Numeric constants</strong> are composed of the digits 0 through 9 and, optionally, a negative sign (for negative numbers), and a decimal point (for floating point numbers). For example, the number -3.14159 is a numeric constant in Python.</p>
<p>A text constant consists of a sequence of characters (also known as a string of characters – or just a string). The following are examples of valid string constants:</p>
<ul>
<li>“A man, a plan, a canal, Panama.”</li>
<li>“Was it Eliot’s toilet I saw?”</li>
<li>“There are 10 kinds of people in this world. Those who know binary, those who don’t, and those who didn’t know it was in base 3!”</li>
</ul>
<p>Note that, unlike Scratch, Python requires the quotes surrounding text constants.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>variable</strong> is a named object that can store a value of a particular data type.</p>
</div>
</div>
<p>Recall that Scratch supports two types of variables: text variables and numeric variables. Moreover, before a variable can be used, its name must be declared. In many programming languages, both its name and type must be declared; however, both Scratch and Python only require a variable’s name to be declared before it is used. Here is an example of declaring and initializing a variable in Python compared to the process in Scratch.</p>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>age <span class="op">=</span> <span class="dv">19</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="images/Lesson04-10.png" class="img-fluid"></p>
</div>
<div id="3fb55031" class="cell quarto-layout-cell" data-execution_count="6" style="flex-basis: 50.0%;justify-content: flex-start;">

</div>
</div>
</div>
<p>Here are some examples that deal with variables and how they compare in Scratch and Python:</p>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>age <span class="op">=</span> <span class="dv">19</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>age <span class="op">=</span> age <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>age <span class="op">=</span> age <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (age <span class="op">&gt;</span> <span class="dv">35</span>):</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"You are old."</span>)</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Young'n!"</span>)</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>num1 <span class="op">=</span> <span class="dv">35</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>num2 <span class="op">=</span> <span class="dv">69</span></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>avg <span class="op">=</span> (num1 <span class="op">+</span> num2) <span class="op">/</span> <span class="fl">2.0</span></span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(avg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="images/Lesson04-11.png" class="img-fluid"></p>
</div>
<div id="0d226833" class="cell quarto-layout-cell" data-execution_count="7" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell-output cell-output-stdout">
<pre><code>Young'n!</code></pre>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="images/Lesson04-12.png" class="img-fluid"></p>
</div>
<div id="dc4dd066" class="cell quarto-layout-cell" data-execution_count="8" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell-output cell-output-stdout">
<pre><code>52.0</code></pre>
</div>
</div>
</div>
</div>
<p>In short, to declare variables in Python, we simply write a statement that assigns a value to a variable name. Note that, just as in Scratch, we can assign a value of a different type to a variable. For example:</p>
<div id="8b9ff3e5" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>var <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(var)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>var <span class="op">=</span> <span class="fl">3.14159</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(var)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>var <span class="op">=</span> <span class="st">"Pi"</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(var)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>5
3.14159
Pi</code></pre>
</div>
</div>
<p>It is important to realize that, while human programmers generally try to give variables names that reflect the use to which they will be put, the variable name itself doesn’t mean anything to the computer. For example, the numeric variable <code>age</code> can be used to hold any number, not just an age. It is perfectly legal for <code>age</code> to hold the number of students in a class or the number of eggs in your refrigerator. The computer couldn’t care less. Human programmers, on the other hand, generally care a great deal. They expect a variable’s name to accurately reflect its purpose; so while it is possible to do so, it would be considered poor programming practice to use the variable <code>age</code> to store anything other than an age.</p>
</section>
<section id="input-and-output-1" class="level3" data-number="20.4">
<h3 data-number="20.4" class="anchored" data-anchor-id="input-and-output-1"><span class="header-section-number">20.4</span> Input and Output</h3>
<p>In order for a computer program to perform any useful work, it must be able to communicate with the outside world. The process of communicating with the outside world is known as input/output (or I/O). Most imperative languages include mechanisms for performing other kinds of I/O such as detecting where the mouse is pointing and accessing the contents of a disk drive.</p>
<p>The flexibility and power that input statements give programming languages cannot be overstated. Without them the only way to get a program to change its output would be to modify the program code itself, which is something that a typical user cannot be expected to do.</p>
<p>General-purpose programming languages allow human programmers to construct programs that do amazing things. When attempting to understand what a program does, however, it is vitally important to always keep in mind that the computer does not comprehend the meaning of the character strings it manipulates or the significance of the calculations it performs. Take, for example, the following simple Scratch program:</p>
<p><img src="images/Lesson04-13.png" class="img-fluid"></p>
<p>This program simply displays strings of characters, stores user input, and echoes that input back to the screen along with some additional character strings. The computer has no clue what the text string “Please enter your name:” means. For all it cares, the string could have been “My hovercraft is full of eels.” or “qwerty uiop asdf ghjkl;” (or any other text string for that matter). Its only concern is to copy the characters of the text string onto the display screen.</p>
<p>Only in the minds of human beings do the sequence of characters “Please enter your name:” take on meaning. If this seems odd, try to remember that comprehension does not even occur in the minds of all humans, only those who are capable of reading and understanding written English. A four year old, for example, would not know how to respond to this prompt because he or she would be unable to read it. This is so despite the fact that if you were to ask the child his or her name, he or she could immediately respond and perhaps even type it out on the keyboard for you.</p>
<p>Now consider this Scratch program:</p>
<p><img src="images/Lesson04-14.png" class="img-fluid"></p>
<p>Here, the input is numeric instead of text. The program prompts the user for two numbers, which it then computes the sum for and displays to the user. Note that two variables were declared: <code>num1</code> and <code>num2</code>. The first number is captured and stored in the variable <code>num1</code>. The second number is captured and stored in the variable <code>num2</code>. What do you think would happen if the user did not provide numeric input and, for example, inputted “Bob” for the first number? In the <em>real world</em>, programmers must create robust programs that examine user input in order to verify that it is of the proper type before processing that input. If the input is found to be in error, the program must take appropriate corrective action, such as rejecting the invalid input and requesting the user try again.</p>
<p>In Python, output is implemented as a <strong>print</strong> statement:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"This is some output!"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>We use the <strong>input</strong> statement to ask a question and obtain user input. In the same statement, we can assign the result of this to a variable:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>age <span class="op">=</span> <span class="bu">int</span>(<span class="bu">input</span>(<span class="st">"How old are you? "</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Of course, we need to take care to properly specify whether the input is numeric or text (in Python 3.x its a text by default. Use casting to convert into numeric).</p>
</section>
<section id="expressions-and-assignment" class="level3" data-number="20.5">
<h3 data-number="20.5" class="anchored" data-anchor-id="expressions-and-assignment"><span class="header-section-number">20.5</span> Expressions and assignment</h3>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>