---
title: "Origin"
date: "August 24, 2023"
toc: true
number-sections: true
format:
  html:
    code-fold: true
jupyter: python3
---

## The Raspberry Pi Platform
Living with Cyber makes use of a unique computing platform that you will
use throughout the curriculum. It consists of a Raspberry Pi computer
(yes, it's a computer), an LCD touchscreen, a keyboard and mouse,
USB-powered speakers, and various other parts. With this platform, you
will complete a variety of hands-on activities. We will try to tie them
all to cyber in some way (this is why we call this curriculum Living
with Cyber). We'll explain what cyber is later.

::: {.callout-note}
We typically use the raspberry pi for the LwC curriculum. Unfortunately
because of supply shortages over the last few years, we have been forced
to pivot and use another type of micro-computer this year. The
alternative we have gone with is a Libre Computer Board or more
affectionately "Le Potato". For the most part, these micro-computers are
interchangeable. However, there might be a place or two where something
that worked in a specific way on a raspberry pi doesn't work the same
way on Le Potato. This will typically be around settings or
configurations. If you come across one such issue, please let your
instructor know so that they can figure out a solution that works for Le
Potato.
:::

## Puzzle-based learning
The curriculum also makes use of **puzzle-based learning**. The idea behind
this learning approach is to utilize puzzles to cultivate problem
solving and critical thinking skills. Puzzles are fun, and if we can
think of large, complicated problems as puzzles, then perhaps we can
actually have fun solving them.  Throughout the curriculum, we will
discuss (and solve) various puzzles. By doing this, we will try to
identify certain tactics that can be used to approach problem solving.
You will also be assigned some to do on your own. It is understandable
that, particularly at first, you may have a hard time solving the
puzzles. We hope that, over time, you will become better at solving
them.

## Videos
The curriculum also makes use of **videos** that are shown in class. They
are intended to be thought- provoking and cover a wide range of topics.
Some relate to interesting applications of computer science; others
cover more philosophical points about learning.

## Some extra rules for this class
Over the years, we have found that it is important to explicitly mention
certain things that might seem obvious to the typical student.

### Taking Exams
Here are a few rules to keep in mind when taking exams:

- No cheating. It's sad that this has to be mentioned; however, it does occur. At the least, you will
earn an F on the exam. At the most, you will earn an F in the course and will be recommended
for expulsion from the university.

- Cell phones must be turned off . They can't even be used as a watch

- No reference material can be used. Exams are closed book and closed notes.

- No sharing of anything. Work the exam on your own. This is your time to show what you (and
only you) have learned and can do.

### Completing Homework and Exams
Here are a few suggestions when completing homework assignments and exams:

- Unless explicitly permitted by the professor, you are **NOT allowed to
  use any AI tools (e.g. chatGPT) for any assignment**. If there is even a
  suspicion that your submission contains any uncited work from an AI
  tool, it will be treated as an attempt at plagiarism which would then
  carry the associated penalties.

- Be clear and concise. Don't vomit words on the page.

- Write legibly. If the prof can't read your writing, it will most likely be marked wrong

- Doodle to elaborate. This is useful to clarify your words. It also helps you to problem solve.

- Format source code properly. On homework, consider taking screenshots of source code.


### Proper email etiquette
The art of good emailing is unfortunately not widespread. Here are a few
things to keep in mind when drafting an email to your prof:

- Make your subjects short and meaningful. We should be able easily
  prioritize it by the subject.

- Make your message short and meaningful. Be concise but also clear.
  Please provide adequate detail to get your message across without
  inducing a puzzled look on your prof's face.
  
- Don't use ALL CAPS. This is rude and quite annoying. It is usually
  taken as yelling.

- Write properly. Use proper spelling, grammar, punctuation, and
  capitalization. Email is not texting.

- Sign your name. Do this at the bottom of your message. Please. Sign.
  Your. Name. The prof can't (and shouldn't) try to figure out who you
  are by looking at your email address. Note that you can automatically
  sign each email by adding a signature.

::: {.callout-note} 
Please make sure to check your *@latech.edu* email **daily**. There are
times when your prof needs to communicate important things to you with
urgency.
:::

### Making the most of oyur time in class

Here are a few things that can help you perform well in class and make
it better for all of us:

- Listen. Don't chitchat with your classmates. This can disrupt the prof
  and your classmates.

- Be active. Take notes, ask questions, work class problems, and help
  others when allowed

- Turn your cell phone off. Or at least set it on vibrate. Don't answer
  it in class. If you must answer, please leave the room before doing
  so.

- Use laptops for class activities. Please don't check Facebook, email,
  the news, play games, etc.

- Take responsibility for your area of the room. Throw away trash around
  you, wipe off dirty tables, tuck your chair in, etc. Basically, just
  be a good human being.

## One Last Thing

Often, students new to the university “life” find it hard to speak to
their professors. Most of us are normal people just like you, and we're
pretty much open to chatting about concerns that you may have about the
course. It is to your advantage (greatly so, in fact) to use your prof's
office hours wisely! If you have questions or need clarity on a problem,
please see your prof during his or her office hours. If your prof's
office hours are not convenient for you (e.g., you have other classes
during that time), please communicate with your prof via email (using
proper email etiquette, of course). We are usually open to setting up an
appointment to accommodate you.

::: {.callout-note}
**Every assignment matters.** Submit all assignments on time. Communicate
with any issues.
:::
  
Lastly, if you do average work on every assignment, activity, exam, etc,
and submit them all on time, it is likely that you will pass the course.
Missing even a single assignment (or, even worse, an exam) will
significantly impact your final grade in the course. Bottom line: every
assignment matters! If you are absent (e.g., due to being sick or
attending some sort of university sponsored activity), please make sure
to communicate with your prof in advance (if you can) via email.
Communication is really important.
